package BinaryTree;

public enum TreeType {
    EMPTY_TREE,
    STANDARD_BST,
    RIGHT_SKEWED_BST,
    STANDARD_BST_ISOMORPH,
    STANDARD_BST_MIRROR,
    BINARY_TREE,
    STANDARD_BST_TWO_NODES_SWAPPED,
    STANDARD_BST_TWO_ADJ_NODES_SWAPPED;
}

